[[exercises]]
question-id = "visualizer-Q2"
title = "Title Placeholder"
difficulty = "Easy"
table = false
multipart= false
type = "visualizer"

question = '''
`This text is pink`
**This text is bold** 

```{code-block} c
#include <stdio.h>

int main(void) {

  printf("This is exercise 2!\n");

  return 0;
}
```
'''

answer = '''
This is exercise 2!
'''
