[[exercises]]
question-id = "visualizer-DF-BEHAVIOR2"
title = "Order Matters in deleteFront"
difficulty = "Easy"
table = false
multipart = false
type = "multiple-choice"

question = '''
In the following code, we store `list->head->next` before `free(list->head)`. Why?

```{code-block} c
Node *newHead = list->head->next;
free(list->head);
list->head = newHead;
```
'''

answer = [1]

choices = [
  "Because `free(list->head)` deletes `list->head`",
  "Because after freeing the head, we lose access to its `next` pointer",
  "It is not necessary",
  "Because freeing memory automatically deletes all remaining nodes"
]
