[[exercises]]
question-id = "chapter13-form-linked-list-q1"
title = "Pointer Reassignment"
difficulty = "Easy"
table = false
multipart = false
type = "visualizer"

question = '''
After executing the following code, what is the value of `temp->data`?

```{code-block} c
Node *head = (Node *)malloc(sizeof(Node));
head->data = 1;

head->next = (Node *)malloc(sizeof(Node));
head->next->data = 2;
head->next->next = NULL;

Node* temp = head->next;
```

A. 1

B. 2

C. 0

D. Runtime error
'''

answer = '''
B
'''
