[[exercises]]
question-id = "chapter13-form-linked-list-q1"
title = "Pointer Reassignment"
difficulty = "Easy"
table = false
multipart = false
type = "visualizer"

question = '''
After executing the following code, what will be printed?

```{code-block} c
Node *head = (Node *)malloc(sizeof(Node));
head->data = 1;
head->next = NULL;

Node *temp = (Node *)malloc(sizeof(Node));
temp->data = 2;
temp->next = NULL;

head = temp;

printf("%d", head->data);
```

A. 1

B. 2

C. 0

D. Runtime error
'''

answer = '''
B
'''
