[[exercises]]
question-id = "chapter9-visualizer-q1"
title = "Pointer Arithmetic in 2D Arrays"
difficulty = "Easy"
table = false
multipart = false
type = "visualizer"

question = '''
Consider the following code snippet for dynamically allocating a 2D array:

```{code-block} c
int Rows = 3;
int Cols = 4;
int** arr = (int**)malloc(sizeof(int*) * Rows);

for (int row = 0; row < Rows; row++) {
  *(arr + row) = (int*)malloc(sizeof(int) * Cols);
}
```

After executing the highlighted line when `row = 2`, what does `*(arr + row)` point to?

```{code-block} c
*(arr + row) = (int*)malloc(sizeof(int) * Cols);
```

A. An invaild address

B. A newly allocated array of integers

C. A newly allocated array of integer pointers 

D. The entire 2D array
'''

answer = '''
B
'''
