[[exercises]]
question-id = "visualizer-LIST-CONCEPT1"
title = "Building the List Correctly"
difficulty = "Easy"
table = false
multipart = false
type = "visualizer"

question = '''
What is the resulting structure of the list?

```{code-block} c
Node *head = createNode(1);
head = createNode(2);
head->next = createNode(4);
```

A. `1 -> 2 -> 4`

B. `2 -> 4`

C. `1 -> 4`

D. Runtime error
'''

answer = '''
B
'''
