[[exercises]]
question-id = "visualizer-LIST-CONCEPT1"
title = "Building the List Correctly"
difficulty = "Easy"
table = false
multipart = false
type = "multiple-choice"

question = '''
What is the resulting structure of the list from `head`?

```{code-block} c
Node *head = createNode(1);
head = createNode(2);
head->next = createNode(4);
```
'''

answer = [1]

choices = [
  "`1 -> 2 -> 4`",
  "`2 -> 4`",
  "`1 -> 4`",
  "Runtime error"
]
